
=head1 NAME

fargo - Removes unseeable and ghost alpha from PNG images, optimized.

=head1 SYNOPSIS

fargo [-h -v -c -s] -i image.png -o output.png

=head1 DESCRIPTION

A lot of digital artists either do not flatten their opaque images before
publishing, or paint directly on transparent backgrounds, which leave very small
amounts of semi-transparent pixels in an image designed to be fully opaque.

Optipng is a good tool for automatically optimizing images, but it doesn't ever
reduce available data. Specifically, if an image has even one pixel with a
different alpha, the entire image will keep the alpha layer, wasting space.

Fargo attempts to remedy this by ignoring the alpha layer, unless there is a
large amount of alpha pixels. This saves a lot of data (15% to 20% normally!),
with no human visible quality loss.

=head1 OPTIONS

B<-h> Display a short help text.

B<-i> E<lt>imageE<gt> The input image to optimize. This flag is required.

B<-o> E<lt>outputE<gt> The output image. This flag is optional.

B<-f> E<lt>factorE<gt> A number between 0 and 1 that changes the threshold of what is considered a "dirty" alpha. Higher is safer. Defaults to 0.975.

B<-v> Enable verbose mode.

B<-c> Enable clobber mode. Ignores output. Will automatically overwrite dirty alphas! DANGEROUS!

B<-s> Run in a simulated mode. Won't automatically overwrite empty alphas. Safe!

=head1 AUTHOR

Daemon Lee Schmidt, with small contributions from Zach Mertes
